'use client';

import Link from 'next/link';
import { animate, useMotionValue, useReducedMotion } from 'framer-motion';
import { useEffect, useId, useMemo, useRef, useState } from 'react';
import {
  DEDUCTIONS,
  INCOME,
  estimateSavings,
  formatUsd,
} from '@/lib/estimateSavings';

/**
 * Hero tax savings estimator.
 *
 * Two native range inputs and a live result card. Native ranges are used
 * deliberately: they are keyboard-operable, screen-reader-labelled, and
 * touch-friendly for free, which a div-and-pointer-events slider is not.
 *
 * GUARDRAIL: every figure here is generated by the visitor's own inputs from
 * a placeholder multiplier — it is not a claim about outcomes the firm has
 * achieved, and the disclaimer beneath the card says so without being
 * dismissible. The maths lives in lib/estimateSavings.ts so the multiplier is
 * a single named constant the client can tune. See README launch checklist.
 *
 * Motion: the figure counts between values through a motion value written
 * straight to the DOM node, so dragging a slider never re-renders on every
 * animation frame. Under prefers-reduced-motion the number is set outright.
 */

/** Where "Get your exact number" sends the visitor. */
const BOOKING_PATH = '/contact';
const BOOKING_HASH = 'consultation-form';

const COUNT_UP_MS = 0.5;

export default function SavingsEstimator({ className = '' }: { className?: string }) {
  const reduce = useReducedMotion();
  const uid = useId();
  const incomeId = `${uid}-income`;
  const deductionsId = `${uid}-deductions`;

  const [income, setIncome] = useState(85_000);
  const [deductions, setDeductions] = useState(3);

  const { savings, fraction } = useMemo(
    () => estimateSavings({ income, deductions }),
    [income, deductions]
  );

  const figureRef = useRef<HTMLSpanElement>(null);
  const displayed = useMotionValue(savings);

  useEffect(() => {
    const node = figureRef.current;
    if (!node) return;

    const paint = (v: number) => {
      node.textContent = formatUsd(Math.round(v));
    };

    if (reduce) {
      displayed.set(savings);
      paint(savings);
      return;
    }

    const unsubscribe = displayed.on('change', paint);
    const controls = animate(displayed, savings, {
      duration: COUNT_UP_MS,
      ease: [0.16, 1, 0.3, 1],
    });

    return () => {
      controls.stop();
      unsubscribe();
    };
  }, [savings, displayed, reduce]);

  const bookingHref = `${BOOKING_PATH}?income=${income}&deductions=${deductions}#${BOOKING_HASH}`;

  return (
    <div
      className={`rounded-2xl border border-white/12 bg-white/[0.05] p-6 backdrop-blur-md sm:p-7 ${className}`}
    >
      <p className="eyebrow">Estimate your savings</p>

      <div className="mt-6 space-y-7">
        <SliderRow
          id={incomeId}
          label="Annual income"
          value={income}
          display={formatUsd(income)}
          min={INCOME.min}
          max={INCOME.max}
          step={INCOME.step}
          minLabel={formatUsd(INCOME.min)}
          maxLabel={`${formatUsd(INCOME.max)}+`}
          onChange={setIncome}
        />

        <SliderRow
          id={deductionsId}
          label="Deductions likely being missed"
          value={deductions}
          display={String(deductions)}
          min={DEDUCTIONS.min}
          max={DEDUCTIONS.max}
          step={DEDUCTIONS.step}
          minLabel="None"
          maxLabel={`${DEDUCTIONS.max}+`}
          onChange={setDeductions}
        />
      </div>

      {/* Result */}
      <div className="mt-8 rounded-xl border border-white/10 bg-ink-900/50 p-5 sm:p-6">
        <p className="font-display text-[0.72rem] font-bold uppercase tracking-[0.16em] text-white/55">
          Potential annual savings
        </p>

        <p
          aria-live="polite"
          aria-atomic="true"
          className="mt-1.5 font-serif text-[2.7rem] font-bold leading-[1.15] tabular-nums text-white sm:text-5xl"
        >
          {/*
            Two nodes on purpose. The visible span is driven imperatively by
            the motion value so the count-up costs no re-renders; the visually
            hidden span carries the settled figure, so assistive tech announces
            the final number once instead of every intermediate frame.
          */}
          <span ref={figureRef} aria-hidden="true">
            {formatUsd(savings)}
          </span>
          <span className="sr-only">{formatUsd(savings)} per year, estimated</span>
        </p>

        <div
          className="mt-5 h-1.5 w-full overflow-hidden rounded-full bg-white/10"
          role="presentation"
        >
          <div
            className="h-full rounded-full bg-accent-bright transition-[width] duration-500 ease-out motion-reduce:transition-none"
            style={{ width: `${Math.round(fraction * 100)}%` }}
          />
        </div>

        <Link href={bookingHref} className="btn-primary mt-6 w-full">
          Get your exact number
        </Link>
      </div>

      <p className="mt-4 text-[0.78rem] leading-relaxed text-white/50">
        Rough estimate for illustration only &mdash; actual savings depend on your
        full tax situation. Not tax advice.
      </p>
    </div>
  );
}

function SliderRow({
  id,
  label,
  value,
  display,
  min,
  max,
  step,
  minLabel,
  maxLabel,
  onChange,
}: {
  id: string;
  label: string;
  value: number;
  display: string;
  min: number;
  max: number;
  step: number;
  minLabel: string;
  maxLabel: string;
  onChange: (value: number) => void;
}) {
  // Drives the filled portion of the track through a CSS custom property, so
  // the gradient stays in step with the thumb without a second element.
  const pct = ((value - min) / (max - min)) * 100;

  return (
    <div>
      <div className="flex items-baseline justify-between gap-4">
        <label htmlFor={id} className="font-display text-[0.9rem] font-semibold text-white/85">
          {label}
        </label>
        <span className="font-display text-[1.05rem] font-bold text-accent-bright">
          {display}
        </span>
      </div>

      <input
        id={id}
        type="range"
        min={min}
        max={max}
        step={step}
        value={value}
        onChange={(e) => onChange(Number(e.target.value))}
        className="estimator-range mt-3 w-full"
        style={{ ['--fill' as string]: `${pct}%` }}
      />

      <div className="mt-2 flex justify-between font-display text-[0.72rem] font-medium text-white/50">
        <span>{minLabel}</span>
        <span>{maxLabel}</span>
      </div>
    </div>
  );
}
