'use client';

import Link from 'next/link';
import { useEffect, useId, useMemo, useRef, useState } from 'react';
import { usePrefersReducedMotion } from '@/lib/usePrefersReducedMotion';
import {
  DEDUCTIONS,
  INCOME,
  estimateSavings,
  formatUsd,
} from '@/lib/estimateSavings';

/**
 * Hero tax savings estimator.
 *
 * Two native range inputs and a live result card. Native ranges are used
 * deliberately: they are keyboard-operable, screen-reader-labelled, and
 * touch-friendly for free, which a div-and-pointer-events slider is not.
 *
 * GUARDRAIL: every figure here is generated by the visitor's own inputs from
 * a placeholder multiplier — it is not a claim about outcomes the firm has
 * achieved, and the disclaimer beneath the card says so without being
 * dismissible. The maths lives in lib/estimateSavings.ts so the multiplier is
 * a single named constant the client can tune. See README launch checklist.
 *
 * Motion: the figure counts between values in a rAF loop that writes straight
 * to the DOM node, so dragging a slider never re-renders on an animation
 * frame. This was framer-motion's `animate`; it is hand-rolled now because
 * that was the last thing on the homepage pulling in the library, and 40KB of
 * animation runtime for one count-up is a bad trade on mobile. Under
 * prefers-reduced-motion the number is set outright.
 */

/** Where "Get your exact number" sends the visitor. */
const BOOKING_PATH = '/contact';
const BOOKING_HASH = 'consultation-form';

const COUNT_UP_MS = 500;

export default function SavingsEstimator({ className = '' }: { className?: string }) {
  const reduce = usePrefersReducedMotion();
  const uid = useId();
  const incomeId = `${uid}-income`;
  const deductionsId = `${uid}-deductions`;

  const [income, setIncome] = useState(85_000);
  const [deductions, setDeductions] = useState(3);

  const { savings, fraction } = useMemo(
    () => estimateSavings({ income, deductions }),
    [income, deductions]
  );

  const figureRef = useRef<HTMLSpanElement>(null);
  /** Where the last run finished, so a new drag eases from the visible value. */
  const fromRef = useRef(savings);

  useEffect(() => {
    const node = figureRef.current;
    if (!node) return;

    const paint = (value: number) => {
      node.textContent = formatUsd(Math.round(value));
    };

    if (reduce) {
      fromRef.current = savings;
      paint(savings);
      return;
    }

    const from = fromRef.current;
    const to = savings;
    if (from === to) {
      paint(to);
      return;
    }

    // Quartic ease-out: quick departure, long settle. Close to the
    // cubic-bezier(0.16, 1, 0.3, 1) this replaced.
    const ease = (t: number) => 1 - Math.pow(1 - t, 4);

    let raf = 0;
    let start = 0;

    const step = (now: number) => {
      if (!start) start = now;
      const t = Math.min((now - start) / COUNT_UP_MS, 1);
      const value = from + (to - from) * ease(t);
      fromRef.current = value;
      paint(value);
      if (t < 1) {
        raf = requestAnimationFrame(step);
      } else {
        fromRef.current = to;
      }
    };

    raf = requestAnimationFrame(step);
    return () => cancelAnimationFrame(raf);
  }, [savings, reduce]);

  const bookingHref = `${BOOKING_PATH}?income=${income}&deductions=${deductions}#${BOOKING_HASH}`;

  return (
    <div
      className={`overflow-hidden rounded-2xl border border-white/12 bg-white/[0.05] backdrop-blur-md ${className}`}
    >
      {/*
        One card, two zones, divided by a hairline rather than nested boxes.
        The earlier version put a bordered card inside a bordered card inside
        the hero, which read as three stacked rectangles.
      */}
      <div className="p-6 sm:p-7">
        <p className="eyebrow">Estimate your savings</p>

        <div className="mt-6 space-y-6">
          <SliderRow
            id={incomeId}
            label="Annual income"
            value={income}
            display={formatUsd(income)}
            min={INCOME.min}
            max={INCOME.max}
            step={INCOME.step}
            minLabel={formatUsd(INCOME.min)}
            maxLabel={`${formatUsd(INCOME.max)}+`}
            onChange={setIncome}
          />

          <SliderRow
            id={deductionsId}
            label="Deductions likely being missed"
            value={deductions}
            display={String(deductions)}
            min={DEDUCTIONS.min}
            max={DEDUCTIONS.max}
            step={DEDUCTIONS.step}
            minLabel="None"
            maxLabel={`${DEDUCTIONS.max}+`}
            onChange={setDeductions}
          />
        </div>
      </div>

      {/* Result zone: full-bleed band, so the card reads as one object. */}
      <div className="border-t border-white/10 bg-ink-900/60 p-6 sm:p-7">
        <p className="font-display text-[0.72rem] font-bold uppercase tracking-[0.16em] text-white/55">
          Potential annual savings
        </p>

        <p
          aria-live="polite"
          aria-atomic="true"
          className="mt-2 flex items-baseline gap-2.5"
        >
          {/*
            Two nodes on purpose. The visible span is driven imperatively by
            the motion value so the count-up costs no re-renders; the visually
            hidden span carries the settled figure, so assistive tech announces
            the final number once instead of every intermediate frame.
          */}
          <span
            ref={figureRef}
            aria-hidden="true"
            className="font-display text-[2.9rem] font-bold leading-[1.1] tracking-[-0.02em] tabular-nums text-white sm:text-[3.25rem]"
          >
            {formatUsd(savings)}
          </span>
          <span
            aria-hidden="true"
            className="font-display text-[0.95rem] font-semibold text-white/45"
          >
            / year
          </span>
          <span className="sr-only">{formatUsd(savings)} per year, estimated</span>
        </p>

        <div
          className="mt-4 h-1 w-full overflow-hidden rounded-full bg-white/10"
          role="presentation"
        >
          <div
            className="h-full rounded-full bg-gradient-to-r from-accent to-accent-bright transition-[width] duration-500 ease-out motion-reduce:transition-none"
            style={{ width: `${Math.round(fraction * 100)}%` }}
          />
        </div>

        <Link href={bookingHref} className="btn-primary mt-6 w-full">
          Get your exact number
        </Link>

        <p className="mt-4 text-[0.76rem] leading-relaxed text-white/50">
          Rough estimate for illustration only &mdash; actual savings depend on
          your full tax situation. Not tax advice.
        </p>
      </div>
    </div>
  );
}

function SliderRow({
  id,
  label,
  value,
  display,
  min,
  max,
  step,
  minLabel,
  maxLabel,
  onChange,
}: {
  id: string;
  label: string;
  value: number;
  display: string;
  min: number;
  max: number;
  step: number;
  minLabel: string;
  maxLabel: string;
  onChange: (value: number) => void;
}) {
  // Drives the filled portion of the track through a CSS custom property, so
  // the gradient stays in step with the thumb without a second element.
  const pct = ((value - min) / (max - min)) * 100;

  return (
    <div>
      <div className="flex items-baseline justify-between gap-4">
        <label
          htmlFor={id}
          className="font-display text-[0.88rem] font-semibold text-white/80"
        >
          {label}
        </label>
        <span className="font-display text-[1.15rem] font-bold tabular-nums text-accent-bright">
          {display}
        </span>
      </div>

      <input
        id={id}
        type="range"
        min={min}
        max={max}
        step={step}
        value={value}
        onChange={(e) => onChange(Number(e.target.value))}
        className="estimator-range mt-2.5 w-full"
        style={{ ['--fill' as string]: `${pct}%` }}
      />

      <div className="mt-1 flex justify-between font-display text-[0.7rem] font-medium text-white/50">
        <span>{minLabel}</span>
        <span>{maxLabel}</span>
      </div>
    </div>
  );
}
